#!/bin/bash

# HealthierKE - Add New Content Types to Existing Data
# This script guides you through adding the new health content types
# to complement your existing articles

echo "🏥 HealthierKE - Add New Health Content Types"
echo "=============================================="
echo ""
echo "✅ You already have great articles about:"
echo "   📄 Malaria in Kenya"
echo "   📄 Tuberculosis (TB) in Kenya"  
echo "   📄 Cervical Cancer in Kenyan Women"
echo "   📄 HIV in Kenya Today"
echo "   📄 High Blood Pressure"
echo "   📄 Typhoid Fever"
echo "   📄 Understanding Diabetes in Kenya"
echo ""
echo "🎯 Now let's add the NEW content types to enhance your platform:"
echo ""

# Function to wait for user confirmation
wait_for_confirmation() {
    read -p "✅ Press Enter when you've completed this step..."
    echo ""
}

echo "🔧 FIRST: Enable Public Access for New Content Types"
echo "===================================================="
echo ""
echo "1. Go to: http://localhost:1337/admin/settings/users-permissions/roles"
echo "2. Click on 'Public' role"
echo "3. Enable these permissions:"
echo "   📋 Health-topic: ✅ find, ✅ findOne"
echo "   🔍 Symptom: ✅ find, ✅ findOne"
echo "   💊 Treatment: ✅ find, ✅ findOne"
echo "4. Click 'Save'"
echo ""

wait_for_confirmation

echo "📋 STEP 1: Create Health Topics (Main Categories)"
echo "================================================"
echo "Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::health-topic.health-topic"
echo ""
echo "Create these 4 main health topics to organize your existing content:"
echo ""

echo "🦠 Infectious Diseases in Kenya"
echo "   - Name: Infectious Diseases in Kenya"
echo "   - Slug: infectious-diseases-kenya"
echo "   - Description: Information about infectious diseases common in Kenya including malaria, TB, typhoid, and HIV."
echo "   - Is Active: ✅ true"
echo "   - Priority: 100"
echo ""

echo "🫀 Non-Communicable Diseases"
echo "   - Name: Non-Communicable Diseases" 
echo "   - Slug: non-communicable-diseases"
echo "   - Description: Information about chronic diseases like diabetes, high blood pressure, and cancer affecting Kenyans."
echo "   - Is Active: ✅ true"
echo "   - Priority: 90"
echo ""

echo "👩 Women's Health in Kenya"
echo "   - Name: Women's Health in Kenya"
echo "   - Slug: womens-health-kenya"
echo "   - Description: Health information specifically relevant to Kenyan women, including cervical cancer prevention."
echo "   - Is Active: ✅ true"
echo "   - Priority: 85"
echo ""

echo "🚨 Emergency Health Conditions"
echo "   - Name: Emergency Health Conditions"
echo "   - Slug: emergency-health-conditions"
echo "   - Description: Critical health conditions requiring immediate medical attention in Kenya."
echo "   - Is Active: ✅ true"
echo "   - Priority: 95"
echo ""

wait_for_confirmation

echo "🩺 STEP 2: Create Conditions (Link to Your Articles)"
echo "===================================================="
echo "Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::condition.condition"
echo ""
echo "Create conditions that match your existing articles:"
echo ""

echo "🦠 Malaria"
echo "   - Name: Malaria"
echo "   - Slug: malaria" 
echo "   - Description: A mosquito-borne infectious disease common in Kenya"
echo "   - Severity: moderate"
echo "   - Is Emergency: false"
echo "   - Color: #E53E3E"
echo "   - Priority: 100"
echo "   - Prevalence in Kenya: Very common, especially in western and coastal regions"
echo ""

echo "🫁 Tuberculosis (TB)"
echo "   - Name: Tuberculosis"
echo "   - Slug: tuberculosis"
echo "   - Description: A bacterial infection that mainly affects the lungs"
echo "   - Severity: severe"
echo "   - Is Emergency: false"
echo "   - Color: #D69E2E"
echo "   - Priority: 95"
echo "   - Prevalence in Kenya: One of the highest TB burdens globally"
echo ""

echo "🩸 High Blood Pressure"
echo "   - Name: High Blood Pressure"
echo "   - Slug: high-blood-pressure"
echo "   - Description: A condition where blood pressure is consistently high"
echo "   - Severity: moderate"
echo "   - Is Emergency: false"
echo "   - Color: #C53030"
echo "   - Priority: 90"
echo "   - Prevalence in Kenya: Affecting about 24% of Kenyan adults"
echo ""

echo "🍯 Diabetes"
echo "   - Name: Diabetes"
echo "   - Slug: diabetes"
echo "   - Description: A group of diseases that result in high blood sugar"
echo "   - Severity: moderate" 
echo "   - Is Emergency: false"
echo "   - Color: #3182CE"
echo "   - Priority: 85"
echo "   - Prevalence in Kenya: Rapidly increasing, affecting 2-3% of adults"
echo ""

echo "👩 Cervical Cancer"
echo "   - Name: Cervical Cancer"
echo "   - Slug: cervical-cancer"
echo "   - Description: Cancer of the cervix, largely preventable with screening"
echo "   - Severity: severe"
echo "   - Is Emergency: false"
echo "   - Color: #B794F6"
echo "   - Priority: 80"
echo "   - Prevalence in Kenya: Leading cause of cancer death in Kenyan women"
echo ""

echo "🤒 Typhoid Fever"
echo "   - Name: Typhoid Fever"
echo "   - Slug: typhoid-fever"
echo "   - Description: A bacterial infection spread through contaminated food/water"
echo "   - Severity: severe"
echo "   - Is Emergency: false"  
echo "   - Color: #38B2AC"
echo "   - Priority: 75"
echo "   - Prevalence in Kenya: Common due to poor sanitation in some areas"
echo ""

echo "🩸 HIV/AIDS"
echo "   - Name: HIV/AIDS"
echo "   - Slug: hiv-aids"
echo "   - Description: Human Immunodeficiency Virus infection"
echo "   - Severity: severe"
echo "   - Is Emergency: false"
echo "   - Color: #805AD5"
echo "   - Priority: 95"
echo "   - Prevalence in Kenya: Approximately 4.9% of adults (much improved from peak)"
echo ""

wait_for_confirmation

echo "🔍 STEP 3: Create Key Symptoms"
echo "==============================="
echo "Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::symptom.symptom"
echo ""
echo "Create common symptoms that link to your conditions:"
echo ""

echo "🤒 Fever"
echo "   - Name: Fever"
echo "   - Slug: fever"
echo "   - Description: Body temperature higher than normal, often indicating infection"
echo "   - Common Severity: mild"
echo "   - Body System: general"
echo "   - When to Seek Care: routine_checkup"
echo "   - Common in Kenya: ✅ true"
echo ""

echo "😴 Persistent Fatigue"
echo "   - Name: Persistent Fatigue"
echo "   - Slug: persistent-fatigue"
echo "   - Description: Ongoing tiredness that doesn't improve with rest"
echo "   - Common Severity: moderate"
echo "   - Body System: general"
echo "   - When to Seek Care: routine_checkup"
echo "   - Common in Kenya: ✅ true"
echo ""

echo "💔 Chest Pain"
echo "   - Name: Chest Pain"
echo "   - Slug: chest-pain"
echo "   - Description: Pain or discomfort in the chest area"
echo "   - Common Severity: severe"
echo "   - Body System: cardiovascular"
echo "   - When to Seek Care: emergency"
echo "   - Common in Kenya: ✅ true"
echo ""

echo "🫁 Persistent Cough"
echo "   - Name: Persistent Cough"
echo "   - Slug: persistent-cough"
echo "   - Description: Cough lasting more than 2-3 weeks"
echo "   - Common Severity: moderate"
echo "   - Body System: respiratory"
echo "   - When to Seek Care: urgent"
echo "   - Common in Kenya: ✅ true"
echo ""

echo "🩸 Unusual Bleeding"
echo "   - Name: Unusual Bleeding"
echo "   - Slug: unusual-bleeding"
echo "   - Description: Abnormal bleeding between periods or after menopause"
echo "   - Common Severity: moderate"
echo "   - Body System: reproductive"
echo "   - When to Seek Care: urgent"
echo "   - Common in Kenya: ✅ true"
echo ""

wait_for_confirmation

echo "💊 STEP 4: Create Common Treatments"
echo "===================================="
echo "Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::treatment.treatment"
echo ""
echo "Create treatments available in Kenya:"
echo ""

echo "💊 Antimalarial Medication"
echo "   - Name: Antimalarial Medication"
echo "   - Slug: antimalarial-medication"
echo "   - Description: Medications to treat and prevent malaria"
echo "   - Type: medication"
echo "   - Estimated Cost: low"
echo "   - Available in Kenya: ✅ true"
echo "   - Requires Prescription: ✅ true"
echo ""

echo "💊 TB Treatment (DOTS)"
echo "   - Name: TB Treatment (DOTS)"
echo "   - Slug: tb-treatment-dots"
echo "   - Description: Directly Observed Treatment Short-course for tuberculosis"
echo "   - Type: medication"
echo "   - Estimated Cost: low"
echo "   - Available in Kenya: ✅ true"
echo "   - Requires Prescription: ✅ true"
echo ""

echo "💊 Blood Pressure Medication"
echo "   - Name: Blood Pressure Medication"
echo "   - Slug: blood-pressure-medication"
echo "   - Description: Medications to control high blood pressure"
echo "   - Type: medication"
echo "   - Estimated Cost: moderate"
echo "   - Available in Kenya: ✅ true"
echo "   - Requires Prescription: ✅ true"
echo ""

echo "🏃 Lifestyle Changes"
echo "   - Name: Lifestyle Changes"
echo "   - Slug: lifestyle-changes"
echo "   - Description: Diet, exercise, and behavior modifications for health"
echo "   - Type: lifestyle"
echo "   - Estimated Cost: low"
echo "   - Available in Kenya: ✅ true"
echo "   - Requires Prescription: false"
echo ""

echo "🩺 Regular Screening"
echo "   - Name: Regular Health Screening"
echo "   - Slug: regular-health-screening"
echo "   - Description: Preventive health checkups and screenings"
echo "   - Type: therapy"
echo "   - Estimated Cost: moderate"
echo "   - Available in Kenya: ✅ true"
echo "   - Requires Prescription: false"
echo ""

wait_for_confirmation

echo "🔗 STEP 5: Link Everything Together"
echo "===================================="
echo ""
echo "Now connect your existing articles to the new content:"
echo ""
echo "1️⃣ Edit your EXISTING ARTICLES:"
echo "   📄 'Malaria in Kenya' → Related Conditions: Malaria"
echo "   📄 'Tuberculosis (TB) in Kenya' → Related Conditions: Tuberculosis"
echo "   📄 'High Blood Pressure' → Related Conditions: High Blood Pressure"
echo "   📄 'Understanding Diabetes' → Related Conditions: Diabetes"
echo "   📄 'Cervical Cancer in Kenyan Women' → Related Conditions: Cervical Cancer"
echo "   📄 'Typhoid Fever' → Related Conditions: Typhoid Fever"
echo "   📄 'HIV in Kenya Today' → Related Conditions: HIV/AIDS"
echo ""
echo "2️⃣ Edit your CONDITIONS to link back:"
echo "   🩺 Each condition → Related Articles: Link to corresponding article"
echo ""
echo "3️⃣ Link SYMPTOMS to CONDITIONS:"
echo "   🤒 Fever → Malaria, Typhoid Fever, TB"
echo "   😴 Persistent Fatigue → HIV/AIDS, Diabetes"
echo "   💔 Chest Pain → High Blood Pressure (emergency cases)"
echo "   🫁 Persistent Cough → Tuberculosis"
echo "   🩸 Unusual Bleeding → Cervical Cancer"
echo ""
echo "4️⃣ Link TREATMENTS to CONDITIONS:"
echo "   💊 Antimalarial Medication → Malaria"
echo "   💊 TB Treatment (DOTS) → Tuberculosis"
echo "   💊 Blood Pressure Medication → High Blood Pressure"
echo "   🏃 Lifestyle Changes → Diabetes, High Blood Pressure"
echo "   🩺 Regular Screening → Cervical Cancer"
echo ""

wait_for_confirmation

echo "🧪 STEP 6: Test Your Enhanced Platform"
echo "======================================"
echo ""
echo "Run this command to test all your new content:"
echo "   ./test-api-phase6.sh"
echo ""
echo "You should now see:"
echo "   📋 Health Topics: 4 topics"
echo "   🩺 Conditions: 7 conditions"
echo "   🔍 Symptoms: 5 symptoms"
echo "   💊 Treatments: 5 treatments"
echo "   📄 Articles: Your existing articles (now enhanced!)"
echo ""

wait_for_confirmation

echo "🎉 CONGRATULATIONS!"
echo "==================="
echo ""
echo "✅ You've successfully enhanced HealthierKE with:"
echo "   📋 4 Health Topics to organize content"
echo "   🩺 7 Conditions matching your existing articles"
echo "   🔍 5 Key symptoms for early detection"
echo "   💊 5 Treatment options available in Kenya"
echo "   🔗 Full relationships between all content"
echo ""
echo "🇰🇪 Your platform now provides:"
echo "   📱 Mobile-optimized health information"
echo "   🚨 Emergency guidance with 999 integration"
echo "   🩺 Medical content validation"
echo "   🔍 Advanced health content search"
echo "   ⚡ High-performance API responses"
echo ""
echo "🚀 HealthierKE is now Kenya's comprehensive health information platform!"
echo ""
echo "📝 Next steps:"
echo "1. Test all the new relationships in the admin panel"
echo "2. Add more symptoms and treatments as needed"
echo "3. Consider adding images/icons to make content more engaging"
echo "4. Test the API endpoints with your frontend application"
echo ""