#!/bin/bash

# Quick Fix for 403 Permission Errors
# This script provides exact steps to enable API access

echo "🔧 QUICK FIX: Enable API Permissions"
echo "====================================="
echo ""
echo "❌ ISSUE: Your new content types are returning 403 Forbidden errors"
echo ""
echo "✅ SOLUTION: Enable public API access in Strapi admin"
echo ""
echo "📋 STEP-BY-STEP FIX:"
echo ""
echo "1️⃣ Open Strapi Admin:"
echo "   🌐 Go to: http://localhost:1337/admin"
echo "   🔐 Login with your admin account"
echo ""
echo "2️⃣ Navigate to Permissions:"
echo "   ⚙️  Settings (left sidebar)"
echo "   👥 Users & Permissions plugin" 
echo "   🏷️  Roles"
echo "   🌍 Click 'Public' role"
echo ""
echo "3️⃣ Enable API Access for New Content Types:"
echo "   📋 Health-topic:"
echo "      ✅ find"
echo "      ✅ findOne"
echo ""
echo "   🔍 Symptom:"
echo "      ✅ find" 
echo "      ✅ findOne"
echo ""
echo "   💊 Treatment:"
echo "      ✅ find"
echo "      ✅ findOne"
echo ""
echo "4️⃣ Save Changes:"
echo "   💾 Click 'Save' button (top right)"
echo "   ⏳ Wait for confirmation message"
echo ""
echo "5️⃣ Test the Fix:"
echo "   🧪 Run: ./test-api-fixed.sh"
echo "   ✅ All content types should now return 200 OK"
echo ""
echo "💡 WHY THIS IS NEEDED:"
echo "By default, Strapi requires authentication for all API endpoints."
echo "Since you want your health content to be publicly accessible"
echo "(for your website/app), we need to enable public access."
echo ""
echo "🔒 SECURITY NOTE:"
echo "This only enables READ access (find/findOne)."
echo "Create/Update/Delete still require authentication."
echo ""
echo "🎯 EXPECTED RESULT AFTER FIX:"
echo "   ✅ Health Topics: 200 OK (instead of 403)"
echo "   ✅ Symptoms: 200 OK (instead of 403)" 
echo "   ✅ Treatments: 200 OK (instead of 403)"
echo "   ✅ Articles: 200 OK (already working)"
echo "   ✅ Conditions: 200 OK (already working)"
echo ""
echo "🚀 Ready to proceed? Press Ctrl+C to exit, or Enter to continue..."
read -p ""
echo ""
echo "✅ After completing the above steps, run:"
echo "   ./test-api-fixed.sh"
echo ""
echo "Then you can add content using:"
echo "   ./add-new-content-types.sh"
echo ""