#!/bin/bash

# HealthierKE Content Population Script
# This script creates sample health content via the Strapi admin panel
# Run this after starting Strapi and setting up an admin user

echo "🏥 HealthierKE Content Population Script"
echo "========================================"
echo ""

# Check if Strapi is running
if ! curl -s http://localhost:1337/admin > /dev/null; then
    echo "❌ Error: Strapi is not running at http://localhost:1337"
    echo "Please start Strapi first with: npm start"
    exit 1
fi

echo "✅ Strapi is running!"
echo ""
echo "📋 Content Population Tasks:"
echo ""
echo "This script will guide you through creating sample health content."
echo "You'll need to create this content manually in the Strapi admin panel."
echo ""

# Function to wait for user confirmation
wait_for_confirmation() {
    read -p "Press Enter when you've completed this task..."
    echo ""
}

echo "1. 🏥 Create Health Topics"
echo "   Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::health-topic.health-topic"
echo ""
echo "   Create these health topics:"
echo ""
echo "   📋 Diabetes Management in Kenya"
echo "   - Name: Diabetes Management in Kenya"
echo "   - Slug: diabetes-management-kenya"
echo "   - Description: Comprehensive information about managing diabetes in the Kenyan context, including local resources and culturally appropriate care strategies."
echo "   - Is Active: true"
echo "   - Priority: 100"
echo ""
echo "   ❤️ Cardiovascular Health"
echo "   - Name: Cardiovascular Health"
echo "   - Slug: cardiovascular-health"
echo "   - Description: Heart health information relevant to Kenyan populations, including prevention and treatment of cardiovascular diseases."
echo "   - Is Active: true"
echo "   - Priority: 90"
echo ""
echo "   🧠 Mental Health & Wellbeing"
echo "   - Name: Mental Health & Wellbeing"
echo "   - Slug: mental-health-wellbeing"
echo "   - Description: Mental health resources and information addressing stigma and promoting mental wellness in Kenya."
echo "   - Is Active: true"
echo "   - Priority: 85"
echo ""
echo "   🫁 Respiratory Health"
echo "   - Name: Respiratory Health"
echo "   - Slug: respiratory-health"
echo "   - Description: Information about respiratory conditions common in Kenya, including prevention and treatment strategies."
echo "   - Is Active: true"
echo "   - Priority: 80"
echo ""

wait_for_confirmation

echo "2. 🩺 Create Sample Conditions"
echo "   Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::condition.condition"
echo ""
echo "   Create these conditions:"
echo ""
echo "   🩸 Type 2 Diabetes"
echo "   - Name: Type 2 Diabetes"
echo "   - Slug: type-2-diabetes"
echo "   - Description: A chronic condition that affects how your body processes blood sugar (glucose)."
echo "   - Severity: moderate"
echo "   - Is Emergency: false"
echo "   - Color: #E53E3E"
echo "   - Priority: 100"
echo "   - Prevalence in Kenya: Common, affecting approximately 2-3% of adults in Kenya"
echo ""
echo "   💔 Heart Attack"
echo "   - Name: Heart Attack"
echo "   - Slug: heart-attack"  
echo "   - Description: A serious medical emergency where the blood supply to the heart is suddenly blocked."
echo "   - Severity: critical"
echo "   - Is Emergency: true"
echo "   - Color: #C53030"
echo "   - Priority: 200"
echo "   - Prevalence in Kenya: Increasing in urban areas due to lifestyle changes"
echo ""
echo "   😰 Depression"
echo "   - Name: Depression"
echo "   - Slug: depression"
echo "   - Description: A mental health condition characterized by persistent feelings of sadness and loss of interest."
echo "   - Severity: moderate"
echo "   - Is Emergency: false"
echo "   - Color: #4A5568"
echo "   - Priority: 90"
echo "   - Prevalence in Kenya: Affects approximately 4-5% of adults, often underdiagnosed"
echo ""
echo "   🫁 Pneumonia"
echo "   - Name: Pneumonia"
echo "   - Slug: pneumonia"
echo "   - Description: An infection that inflames air sacs in one or both lungs."
echo "   - Severity: severe"
echo "   - Is Emergency: false"
echo "   - Color: #2B6CB0"
echo "   - Priority: 95"
echo "   - Prevalence in Kenya: Leading cause of death in children under 5"
echo ""

wait_for_confirmation

echo "3. 🔍 Create Sample Symptoms"
echo "   Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::symptom.symptom"
echo ""
echo "   Create these symptoms:"
echo ""
echo "   💧 Excessive Thirst"
echo "   - Name: Excessive Thirst"
echo "   - Slug: excessive-thirst"
echo "   - Description: Drinking more water than usual and still feeling thirsty."
echo "   - Common Severity: mild"
echo "   - Body System: endocrine"
echo "   - When to Seek Care: routine_checkup"
echo "   - Common in Kenya: true"
echo ""
echo "   💔 Chest Pain"
echo "   - Name: Chest Pain"
echo "   - Slug: chest-pain"
echo "   - Description: Discomfort or pain in the chest area that may indicate a serious condition."
echo "   - Common Severity: severe"
echo "   - Body System: cardiovascular"
echo "   - When to Seek Care: emergency"
echo "   - Common in Kenya: true"
echo ""
echo "   😢 Persistent Sadness"
echo "   - Name: Persistent Sadness"
echo "   - Slug: persistent-sadness"
echo "   - Description: Ongoing feelings of sadness that last for weeks or months."
echo "   - Common Severity: moderate"
echo "   - Body System: nervous"
echo "   - When to Seek Care: routine_checkup"
echo "   - Common in Kenya: true"
echo ""
echo "   🫁 Difficulty Breathing"
echo "   - Name: Difficulty Breathing"
echo "   - Slug: difficulty-breathing"
echo "   - Description: Shortness of breath or feeling like you can't get enough air."
echo "   - Common Severity: severe"
echo "   - Body System: respiratory"
echo "   - When to Seek Care: urgent"
echo "   - Common in Kenya: true"
echo ""

wait_for_confirmation

echo "4. 💊 Create Sample Treatments"
echo "   Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::treatment.treatment"
echo ""
echo "   Create these treatments:"
echo ""
echo "   💊 Metformin"
echo "   - Name: Metformin"
echo "   - Slug: metformin"
echo "   - Description: A medication commonly used to treat type 2 diabetes by lowering blood glucose levels."
echo "   - Type: medication"
echo "   - Estimated Cost: moderate"
echo "   - Available in Kenya: true"
echo "   - Requires Prescription: true"
echo ""
echo "   🚑 Emergency Cardiac Care"
echo "   - Name: Emergency Cardiac Care"
echo "   - Slug: emergency-cardiac-care"
echo "   - Description: Immediate medical treatment for heart attack or cardiac emergency."
echo "   - Type: emergency"
echo "   - Estimated Cost: high"
echo "   - Available in Kenya: true"
echo "   - Requires Prescription: false"
echo ""
echo "   💬 Counseling Therapy"
echo "   - Name: Counseling Therapy"
echo "   - Slug: counseling-therapy"
echo "   - Description: Professional mental health counseling to address depression and anxiety."
echo "   - Type: therapy"
echo "   - Estimated Cost: moderate"
echo "   - Available in Kenya: true"
echo "   - Requires Prescription: false"
echo ""
echo "   💊 Antibiotics for Pneumonia"
echo "   - Name: Antibiotics for Pneumonia"
echo "   - Slug: antibiotics-pneumonia"
echo "   - Description: Antibiotic treatment for bacterial pneumonia infections."
echo "   - Type: medication"
echo "   - Estimated Cost: low"
echo "   - Available in Kenya: true"
echo "   - Requires Prescription: true"
echo ""

wait_for_confirmation

echo "5. 📄 Create Sample Articles"
echo "   Navigate to: http://localhost:1337/admin/content-manager/collection-types/api::article.article"
echo ""
echo "   Create these articles:"
echo ""
echo "   📋 Understanding Type 2 Diabetes in Kenya"
echo "   - Title: Understanding Type 2 Diabetes in Kenya"
echo "   - Slug: understanding-type-2-diabetes-kenya"
echo "   - Description: A comprehensive guide to understanding, managing, and living with Type 2 diabetes in the Kenyan context."
echo "   - Article Type: overview"
echo "   - Target Audience: general_public"
echo "   - Priority: 100"
echo "   - Medically Reviewed: true"
echo "   - Health Disclaimer: true"
echo "   - Reading Time: 10"
echo ""
echo "   🚨 Recognizing Heart Attack Signs"
echo "   - Title: Recognizing Heart Attack Signs: Act Fast, Save Lives"
echo "   - Slug: recognizing-heart-attack-signs"
echo "   - Description: Critical information about recognizing heart attack symptoms and taking immediate action."
echo "   - Article Type: emergency"
echo "   - Target Audience: general_public"
echo "   - Priority: 200"
echo "   - Medically Reviewed: true"
echo "   - Health Disclaimer: true"
echo "   - Reading Time: 5"
echo ""
echo "   🧠 Mental Health Matters in Kenya"
echo "   - Title: Mental Health Matters: Breaking the Stigma in Kenya"
echo "   - Slug: mental-health-matters-kenya"
echo "   - Description: Addressing mental health stigma and promoting awareness of mental health resources in Kenya."
echo "   - Article Type: overview"
echo "   - Target Audience: general_public"
echo "   - Priority: 90"
echo "   - Medically Reviewed: true"
echo "   - Health Disclaimer: true"
echo "   - Reading Time: 8"
echo ""
echo "   🫁 Preventing Pneumonia in Children"
echo "   - Title: Preventing Pneumonia in Children: A Parent's Guide"
echo "   - Slug: preventing-pneumonia-children"
echo "   - Description: Essential information for parents on preventing pneumonia in children and recognizing warning signs."
echo "   - Article Type: prevention"
echo "   - Target Audience: caregivers"
echo "   - Priority: 85"
echo "   - Medically Reviewed: true"
echo "   - Health Disclaimer: true"
echo "   - Reading Time: 12"
echo ""

wait_for_confirmation

echo "6. 🔗 Create Content Relationships"
echo ""
echo "   Now link the content together by editing each item and adding relationships:"
echo ""
echo "   📋 Health Topics → Related Conditions:"
echo "   - Diabetes Management → Type 2 Diabetes"
echo "   - Cardiovascular Health → Heart Attack"
echo "   - Mental Health & Wellbeing → Depression"
echo "   - Respiratory Health → Pneumonia"
echo ""
echo "   📄 Articles → Related Conditions:"
echo "   - Understanding Type 2 Diabetes → Type 2 Diabetes"
echo "   - Recognizing Heart Attack Signs → Heart Attack"
echo "   - Mental Health Matters → Depression"
echo "   - Preventing Pneumonia → Pneumonia"
echo ""
echo "   🔍 Symptoms → Related Conditions:"
echo "   - Excessive Thirst → Type 2 Diabetes"
echo "   - Chest Pain → Heart Attack"
echo "   - Persistent Sadness → Depression"
echo "   - Difficulty Breathing → Pneumonia, Heart Attack"
echo ""
echo "   💊 Treatments → Related Conditions:"
echo "   - Metformin → Type 2 Diabetes"
echo "   - Emergency Cardiac Care → Heart Attack"
echo "   - Counseling Therapy → Depression"
echo "   - Antibiotics for Pneumonia → Pneumonia"
echo ""

wait_for_confirmation

echo "7. ✅ Test API Endpoints"
echo ""
echo "   Test these API endpoints to verify everything is working:"
echo ""
echo "   📋 Health Topics:"
echo "   curl 'http://localhost:1337/api/health-topics'"
echo ""
echo "   🩺 Conditions:"
echo "   curl 'http://localhost:1337/api/conditions'"
echo ""
echo "   📄 Articles:"
echo "   curl 'http://localhost:1337/api/articles'"
echo ""
echo "   🔍 Symptoms:"
echo "   curl 'http://localhost:1337/api/symptoms'"
echo ""
echo "   💊 Treatments:"
echo "   curl 'http://localhost:1337/api/treatments'"
echo ""

wait_for_confirmation

echo "🎉 Content Population Complete!"
echo ""
echo "✅ Created sample health topics"
echo "✅ Created sample conditions with different severity levels"
echo "✅ Created sample symptoms linked to conditions"
echo "✅ Created sample treatments with Kenya availability info"
echo "✅ Created sample articles with proper medical review flags"
echo "✅ Linked all content with proper relationships"
echo "✅ Tested API endpoints"
echo ""
echo "🚀 Your HealthierKE system is now ready for testing with sample data!"
echo "📱 You can now test the mobile-optimized responses and error handling."
echo "🔍 Try searching for content and testing the emergency content features."
echo ""
echo "Next steps:"
echo "1. Test the admin interface usability"
echo "2. Verify all relationships work correctly"
echo "3. Test API response optimization for mobile"
echo "4. Test emergency content handling"
echo ""